---
title: "Fig. 2 | Standardized effect sizes of predictor variables for species description, geolocation, and sequencing in global freshwater fishes"
author: 
  - "Liuyong Ding"
  - "Institute of Hydrobiology, Chinese Academy of Sciences"
  - "Email: `ly_ding@126.com`" 
date: "`r Sys.Date()`"    
fontsize: 12              
geometry: "margin=1in"    
output: 
  prettydoc::html_pretty:
    theme: cayman  # Specify a different theme if 'cayman' is unavailable
    highlight: github  # Specify a supported highlight style
---

```{r setup-libraries}
# Load necessary libraries
library(bayesplot)     # For Bayesian plot visualization
library(rstanarm)      # For Bayesian regression models
library(ggplot2)       # For general plotting
library(dplyr)         # Data manipulation verbs
library(brms)          # Interface for Bayesian multilevel models
library(posterior)     # For posterior analysis tools
library(ggh4x)         # For handling multi-panel grid plots
library(ggtext)        # For handling markdown text in ggplot2
library(magrittr)      # For piping operations
library(tidyr)         # For data tidying
library(sf)            # For spatial data handling
library(ggspatial)     # For spatial transformations
library(rnaturalearth) # For world map data
library(patchwork)     # For combining plots
library(here)             # Find your files
library(prettydoc)        # Creating Pretty HTML

# Suppress warnings
options(warn = -1)

# Set options
options(sf_use_s2 = F)   # Disable spherical geometry for sf package
```

```{r setup, include=FALSE}
# Load data
posterior_summary <- readRDS(here("data","posterior_summary.rds"))  # Load posterior summary data
inland <- readRDS(here("data","inland.rds"))  # Load inland regions data

# Define Group Labels for ggh4x (Group categories based on variable types)
posterior_summary$group <- case_when(
  posterior_summary$variable %in% c("Sampling effort", "Human density", "Preserved specimen", "Sequencing effort", "Taxonomic activity", "Taxonomic effort") ~ "Sociological",
  posterior_summary$variable %in% c("Elevation", "Precipitation seasonality", "Temperature seasonality", "Annual precipitation", "Annual temperature") ~ "Environmental",
  TRUE ~ "Biological"
)

# Convert 'group' into a factor with specific order
posterior_summary$group <- factor(posterior_summary$group, levels = c("Sociological", "Environmental", "Biological"))

# Set the ecoregions as factors with a specific order
posterior_summary$ecoregion <- factor(posterior_summary$ecoregion, levels = c("Nearctic", "Neotropic", "Palearctic", "Afrotropic", "Indomalayan", "Australasian", "Oceanian", "Global"))

# Reorder variables to have a logical factor order
posterior_summary$variable <- factor(posterior_summary$variable, levels = c(
  "Sampling effort", "Human density", "Preserved specimen", "Sequencing effort", "Taxonomic activity", "Taxonomic effort",
  "Elevation", "Precipitation seasonality", "Temperature seasonality", "Annual precipitation", "Annual temperature",
  "Range rarity", "Range size", "Body size"
))

# Replace shortfall names for consistency
posterior_summary$shortfall <- ifelse(posterior_summary$shortfall == "Darwinian", "Sequencing", posterior_summary$shortfall)
posterior_summary$shortfall <- ifelse(posterior_summary$shortfall == "Wallacean", "Geolocation", posterior_summary$shortfall)
posterior_summary$shortfall <- ifelse(posterior_summary$shortfall == "Linnaean", "Description", posterior_summary$shortfall)
posterior_summary$shortfall <- factor(posterior_summary$shortfall, levels = c("Sequencing", "Geolocation", "Description"))
```

```{r,fig.width=20/2.54, fig.height=20/2.54}
# Set custom colors for the shortfall types
set2_colors <- c("Description" = "#D55E00", "Geolocation" = "#009E73", "Sequencing" = "#435792")

# Plot the posterior summary with customized color scheme
p <- ggplot(data = posterior_summary, aes(x = Estimate, y = interaction(variable, group), fill = shortfall)) +
  annotate("rect", ymin = 0.5, ymax = 6.5, xmin = -Inf, xmax = Inf, fill = "#A3473E", alpha = 0.1) +  # Add background color for Sociological group
  annotate("rect", ymin = 6.5, ymax = 11.5, xmin = -Inf, xmax = Inf, fill = "#6D4D80", alpha = 0.1) +  # Add background color for Environmental group
  annotate("rect", ymin = 11.5, ymax = 14.5, xmin = -Inf, xmax = Inf, fill = "#6C8F5D", alpha = 0.1) +  # Add background color for Biological group
  # 95% Credible Interval (CrI)
  geom_pointrange(aes(x = Estimate, xmin = Q2.5, xmax = Q97.5, fill = shortfall, color = shortfall),
                  position = position_dodge(0.6), linewidth = 0.5, shape = 21, stroke = 0.2, size = 0.46) +  # Point range plot for the estimates with credible intervals
  geom_vline(xintercept = 0, linetype = 2, size = 0.4, color = "gray50") +  # Add a vertical line at zero for reference
  scale_fill_manual(name = "First documentation", values = set2_colors, limits = c("Description", "Geolocation", "Sequencing")) +  # Set custom colors for fill
  scale_color_manual(name = "First documentation", values = set2_colors, limits = c("Description", "Geolocation", "Sequencing")) +  # Set custom colors for color
  theme_classic() +  # Use a classic theme
  facet_wrap(. ~ ecoregion, nrow = 1, scales = "free_x") +  # Create faceting by ecoregion with independent x scales
  scale_x_continuous(breaks = c(-2, 0, 2, 4, 6)) +  # Set x-axis breaks
  scale_y_discrete(expand = c(0, 0), guide = "axis_nested") +  # Set y-axis for nested axis
  theme(strip.background = element_blank(),  # Remove background for facet strips
        legend.title = element_text(colour = "black", size = 9),  # Customize legend title
        legend.text = element_text(colour = "black", size = 8),  # Customize legend text
        legend.key.height = unit(0.5, "cm"),  # Adjust legend key height
        axis.title = element_text(colour = "black", size = 10),  # Customize axis titles
        axis.text.x = element_text(colour = "black", size = 8),  # Customize x-axis text
        strip.text = element_text(size = 8),  # Customize strip text
        axis.text.y = element_text(size = 8, colour = c(rep("#A3473E", 6), rep("#6D4D80", 5), rep("#6C8F5D", 3))),  # Use colors for y-axis text
        ggh4x.axis.nestline.y = element_line(colour = c("#A3473E", "#6D4D80", "#6C8F5D")),  # Set color for y-axis nesting lines
        ggh4x.axis.nesttext.y = element_text(colour = c("#A3473E", "#6D4D80", "#6C8F5D"), angle = 90, size = 10, hjust = 0.5)) +  # Customize nested axis text appearance
  ylab("") +  # Remove y-axis label
  xlab("Standardized coefficient (95% CI)")  # x-axis label for standardized coefficients with 95% CI

p
```

```{r,fig.width=20/2.54, fig.height=18/2.54}
# Additional map-related libraries and data processing
# Group inland regions by ecoregion
inland_grouped <- inland %>%
  group_by(Ecoregion) %>%
  summarise(geometry = st_union(geometry), .groups = "drop")  # Combine geometries by ecoregion
inland_grouped_fixed <- st_wrap_dateline(inland_grouped, options = c("WRAPDATELINE=YES"))  # Handle date line wrapping

# Get world map (for background)
world <- ne_countries(scale = "small", returnclass = "sf") %>%
  st_wrap_dateline(options = c("WRAPDATELINE=YES"))  # Wrap world map at date line

p4 <- ggplot() +
  geom_sf(data = world, fill = "gray80", color = NA, size = 0.2) +  # 世界地图
  geom_sf(data = filter(inland_grouped_fixed, Ecoregion == "Afrotropic"), fill = "#D55E00", color = NA, size = 0.5) +  # 高亮该 Ecoregion
  coord_sf(crs = "+proj=laea +lon_0=15 +lat_0=0")+
  theme_minimal() +
  theme(axis.text = element_blank(),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_line(color = "#ebebe5", size = 0.01))

p6 <- ggplot() +
  geom_sf(data = world, fill = "gray80", color = NA, size = 0.2) +  # 世界地图
  geom_sf(data = filter(inland_grouped_fixed, Ecoregion == "Australasia"), fill = "#0072B2", color = NA, size = 0.5) +  # 高亮该 Ecoregion
  coord_sf(crs = "+proj=laea +lon_0=140 +lat_0=0")+
  theme_minimal() +
  theme(axis.text = element_blank(),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_line(color = "#ebebe5", size = 0.01))


p5 <- ggplot() +
  geom_sf(data = world, fill = "gray80", color = NA, size = 0.2) +  # 世界地图
  geom_sf(data = filter(inland_grouped_fixed, Ecoregion == "Indomalayan"), fill = "#009E73", color = NA, size = 0.5) +  # 高亮该 Ecoregion
  coord_sf(crs = "+proj=laea +lon_0=90 +lat_0=10")+
  theme_minimal() +
  theme(axis.text = element_blank(),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_line(color = "#ebebe5", size = 0.01))

#filter(inland_grouped_fixed, Ecoregion == "Nearctic") %>% st_centroid() %>% st_coordinates()

p1 <- ggplot() +
  geom_sf(data = world, fill = "gray80", color = NA, size = 0.2) +  # 世界地图
  geom_sf(data = filter(inland_grouped_fixed, Ecoregion == "Nearctic"), fill = "#F0E442", color = NA, size = 0.5) +  # 高亮该 Ecoregion
  coord_sf(crs = "+proj=laea +lon_0=-100 +lat_0=30")+
  theme_minimal() +
  theme(axis.text = element_blank(),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_line(color = "#ebebe5", size = 0.01))

#filter(inland_grouped_fixed, Ecoregion == "Neotropic") %>% st_centroid() %>% st_coordinates()
p2 <- ggplot() +
  geom_sf(data = world, fill = "gray80", color = NA, size = 0.2) +  # 世界地图
  geom_sf(data = filter(inland_grouped_fixed, Ecoregion == "Neotropic"), fill = "#E69F00", color = NA, size = 0.5) +  # 高亮该 Ecoregion
  coord_sf(crs = "+proj=laea +lon_0=-90 +lat_0=0")+
  theme_minimal() +
  theme(axis.text = element_blank(),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_line(color = "#ebebe5", size = 0.01))


#filter(inland_grouped_fixed, Ecoregion == "Oceania") %>% st_centroid() %>% st_coordinates()
p7 <- ggplot() +
  geom_sf(data = world, fill = "gray80", color = NA, size = 0.2) +  # 世界地图
  geom_sf(data = filter(inland_grouped_fixed, Ecoregion == "Oceania"), fill = "#56B4E9", color = NA, size = 0.5) +  # 高亮该 Ecoregion
  #coord_sf(crs = "+proj=ortho +lon_0=-170 +lat_0=0")+
  coord_sf(crs = "+proj=laea +lon_0=180 +lat_0=0")+
  theme_minimal() +
  theme(axis.text = element_blank(),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_line(color = "#ebebe5", size = 0.01))

#filter(inland_grouped_fixed, Ecoregion == "Palearctic") %>% st_centroid() %>% st_coordinates()
p3 <- ggplot() +
  #geom_sf(data = graticules, color = "black", size = 0.6) +  # 额外绘制经纬网格
  geom_sf(data = world, fill = "gray80", color = NA, size = 0) +  # 世界地图
  geom_sf(data = filter(inland_grouped_fixed, Ecoregion == "Palearctic"), fill = "#CC79A7", color = NA, size = 0) +  # 高亮该 Ecoregion
  coord_sf(crs = "+proj=laea +lon_0=70 +lat_0=30")+
  theme_void() +
  theme(axis.text = element_blank(),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_line(color = "#ebebe5", size = 0.01))


p8 <- ggplot() +
  geom_sf(data = world, fill = "gray80", color = NA, size = 0.2) +  # 世界地图
  geom_sf(data = inland_grouped_fixed,aes(fill = Ecoregion), color = NA, size = 0.5, show.legend = F) +  
  scale_fill_manual(values = c(
    "Afrotropic" = "#D55E00",
    "Australasia" = "#0072B2",
    "Indomalayan" = "#009E73",
    "Nearctic" = "#F0E442",
    "Neotropic" = "#E69F00",
    "Oceania" = "#56B4E9",
    "Palearctic" = "#CC79A7"
  ))+
  coord_sf(crs = "+proj=laea +lat_0=52 +lon_0=10 +x_0=4321000 +y_0=3210000 +datum=WGS84 +units=m +no_defs")+
  theme_minimal() +
  theme(axis.text = element_blank(),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_line(color = "#ebebe5", size = 0.01))

pp <- p1 +p2 +p3 +p4 +p5+p6+p7+p8 +plot_layout(nrow = 1) &
  theme(margin(0, 0, 0, 0))

# Combine the map plot with the posterior summary plot (p)
pp / p + plot_layout(heights = c(0.2, 0.8)) & 
  theme(legend.position = c(-0.12, 1.11),  # Adjust legend position
        plot.margin = unit(c(0, 0.1, 0.1, 0), "cm"))  # Adjust plot margins

# Save the final combined plot as a high-resolution image
ggsave(here("images","Figure2.png"), dpi = 600, units = "cm", width = 20, height = 18)  # Save figure at 600 DPI

```

```{r}
sessionInfo()
```